### ISSUE TITLE
Error on 1:1 network

### ISSUE THREAD

**Issue by ewg118** [d3plus/d3plus-network#67] opened 2020-11-05 15:43 UTC
I am working on implementing the Network library and am getting a `Uncaught TypeError: e is null` error when there is a 1:1 network, as in there are only two nodes with only one link in between. I find that 1:n networks render fine. You should be able to replicate this with your own example by reducing the nodes object to 2 items and reducing the links to only one object with a `{source : 0, target : 1}`.

**Comment by davelandry** [comment] 2020-12-08 14:29
@ewg118 I'm unable to reproduce this with the current version of d3plus-network. Are you able to reproduce your error in a jsfiddle? Here's the code I used for testing:

```js
var nodes = [
  {id: "alpha", x: 1, y: 1},
  {id: "beta", x: 2, y: 1}
];

var links = [
  {source: 0, target: 1}
];

const network = new d3plus.Network()
  .links(links)
  .nodes(nodes)
  .render();
```

**Comment by ewg118** [comment] 2020-12-08 14:41
How about this? https://jsfiddle.net/agzw2vfe/

**Comment by davelandry** [comment] 2020-12-08 15:59
Ahh interesting, it only happens with automatic x/y layout. Thanks, should be able to fix this now.

**Comment by davelandry** [comment] 2020-12-08 16:24
@ewg118 fixed with d3plus-network v0.6.1 🎉

**Closed** 2020-12-08 16:23 UTC
Labels: bug

**Comment by ewg118** [comment] 2020-12-08 16:39
Thanks! Will there be an updated minimized js file?

**Comment by davelandry** [comment] 2020-12-08 21:50
Yup! It just takes it a few minutes to be generated: https://d3plus.org/js/d3plus-network.v0.6.full.min.js

**Comment by ewg118** [comment] 2020-12-08 22:01
Thanks! I have confirmed it's now working in production.
